export const dict = {
  en: {
    brand: 'Al Mizan', brandSub: 'Case Investigation',
    navHow: 'How it works', navTrust: 'Built for attorneys', navLaunch: 'Open the tool',
    heroEyebrow: 'Internal tool for attorneys — not client-facing',
    heroTitle: 'Eight specialist agents, one reviewed case file.',
    heroLede: 'Research, court routing, and citation verification handled for you — with an attorney review gate before anything is ever treated as final. Nothing here files itself.',
    heroPrimary: 'Open the investigation tool', heroSecondary: 'See how it works',
    howEyebrow: 'How it works',
    howTitle: 'A pipeline, not a black box',
    howLede: 'Each stage is a separate, specialist agent with one job. Verification stages are blocking — nothing advances until they pass.',
    a1t: 'Intake', a1d: 'Extracts parties, claims, and dates from your case narrative, each with a source anchor back to your original text.',
    a2t: 'Research', a2d: 'Finds applicable statutes and case law for the claim, from a jurisdiction-specific corpus.',
    a3t: 'Court-Routing', a3d: 'Determines the correct court and filing fee — a table lookup, never a guess.',
    a4t: 'Drafting', a4d: 'Generates the required legal documents, citing only verified authority.',
    a5t: 'Citation Verification', a5d: 'An independent pass — re-checks every citation against the source corpus. Blocking.',
    a6t: 'Fact-Consistency', a6d: 'Confirms the draft matches the facts you gave it, tiered by how much judgment is involved.',
    a7t: 'Assembler', a7d: 'Compiles everything into one structured case package with a full audit trail.',
    a8t: 'Attorney Review Gate', a8d: 'Nothing is final, filed, or sent anywhere until you approve it.',
    trustEyebrow: 'Built for the office, not the public',
    trustTitle: 'Attorney-assist, not autonomous filing',
    trustLede: 'This is an internal case-management tool for your practice — not a client-facing product, and not a substitute for your judgment.',
    t1h: 'You review everything', t1d: 'Every draft, citation, and routing decision is a proposal. Nothing reaches a court without your explicit approval.',
    t2h: 'Full audit trail', t2d: 'Every agent action is logged — what it found, what it decided, and when — so you can always see how a document came together.',
    t3h: 'Jurisdiction-aware by design', t3d: 'Built so the same pipeline can run against different countries\' legal data, starting with Jordan.',
    stubTitle: 'Current status: real pipeline, placeholder legal data',
    stubBody: 'The agent pipeline, verification logic, and audit trail are all real. The legal corpus and fee schedule behind Research and Court-Routing are a small, clearly-labeled placeholder set for testing — not verified legal content. Do not use this for real filings yet.',
    footer: 'Al Mizan Legal Practice — internal tool. Not for client or public use.',
    langToggle: 'العربية'
  },
  ar: {
    brand: 'الميزان', brandSub: 'تحقيق القضية',
    navHow: 'آلية العمل', navTrust: 'مصمم للمحامين', navLaunch: 'فتح الأداة',
    heroEyebrow: 'أداة داخلية للمحامين — ليست موجهة للعملاء',
    heroTitle: 'ثمانية وكلاء متخصصون، ملف قضية واحد مُراجَع.',
    heroLede: 'البحث القانوني وتحديد المحكمة والتحقق من الاستشهادات، كلها تتم نيابة عنك — مع بوابة مراجعة إلزامية من المحامي قبل اعتماد أي شيء كنهائي. لا شيء هنا يُقدَّم من تلقاء نفسه.',
    heroPrimary: 'فتح أداة التحقيق', heroSecondary: 'شاهد آلية العمل',
    howEyebrow: 'آلية العمل',
    howTitle: 'مسار عمل، وليس صندوقًا أسود',
    howLede: 'كل مرحلة وكيل متخصص منفصل بمهمة واحدة. مراحل التحقق إلزامية — لا يتقدم الملف حتى تنجح.',
    a1t: 'الإدخال', a1d: 'يستخرج الأطراف والدعاوى والتواريخ من سرد قضيتك، كل حقيقة مرتبطة بمصدرها في نصك الأصلي.',
    a2t: 'البحث القانوني', a2d: 'يجد المواد القانونية والسوابق القضائية المنطبقة على الدعوى من قاعدة بيانات خاصة بكل اختصاص قضائي.',
    a3t: 'تحديد المحكمة', a3d: 'يحدد المحكمة الصحيحة ورسوم التقديم — بحث في جدول مرجعي، وليس تخمينًا.',
    a4t: 'الصياغة', a4d: 'يُنشئ المستندات القانونية المطلوبة، بالاستشهاد فقط بمصادر موثّقة.',
    a5t: 'التحقق من الاستشهادات', a5d: 'فحص مستقل — يعيد التحقق من كل استشهاد مقابل القاعدة القانونية. إلزامي.',
    a6t: 'الاتساق الواقعي', a6d: 'يتأكد من أن المسودة تطابق الوقائع التي قدمتها، مصنّفة حسب مقدار الحكم الشخصي المطلوب.',
    a7t: 'التجميع', a7d: 'يجمّع كل شيء في ملف قضية واحد مهيكل مع سجل تدقيق كامل.',
    a8t: 'بوابة مراجعة المحامي', a8d: 'لا شيء نهائي أو مُقدَّم أو مُرسَل حتى توافق عليه.',
    trustEyebrow: 'مصمم للمكتب، وليس للجمهور',
    trustTitle: 'مساعدة للمحامي، وليست تقديمًا ذاتيًا',
    trustLede: 'هذه أداة داخلية لإدارة القضايا لمكتبك — وليست منتجًا موجهًا للعملاء، وليست بديلاً عن حكمك المهني.',
    t1h: 'أنت تراجع كل شيء', t1d: 'كل مسودة واستشهاد وقرار توجيه هو مجرد اقتراح. لا شيء يصل إلى المحكمة دون موافقتك الصريحة.',
    t2h: 'سجل تدقيق كامل', t2d: 'يتم تسجيل كل إجراء لكل وكيل — ما وجده، وما قرره، ومتى — حتى تتمكن دائمًا من رؤية كيفية تكوّن المستند.',
    t3h: 'مصمم ليكون واعيًا بالاختصاص القضائي', t3d: 'مبني بحيث يمكن لنفس المسار أن يعمل مع بيانات قانونية من دول مختلفة، بدءًا من الأردن.',
    stubTitle: 'الوضع الحالي: مسار عمل حقيقي، بيانات قانونية تجريبية',
    stubBody: 'مسار الوكلاء ومنطق التحقق وسجل التدقيق كلها حقيقية. أما القاعدة القانونية وجدول الرسوم خلف البحث القانوني وتحديد المحكمة فهي مجموعة تجريبية صغيرة ومُعلَّمة بوضوح لأغراض الاختبار — وليست محتوى قانونيًا موثّقًا. لا تستخدم هذا لتقديمات حقيقية بعد.',
    footer: 'الميزان لممارسة القانون — أداة داخلية. غير مخصصة لاستخدام العملاء أو الجمهور.',
    langToggle: 'English'
  }
};
